config/routes.rb
Rails.application.routes.draw do

  # wechat pay test
  # get 'testpay/js_api_call_pay' => 'pay#pay'
  get 'wechatpay/js_api_call_pay' => 'pay#pay'
  get 'pay/success' => 'pay#pay_success'
  # post 'testpay/notify' => 'pay#notify'
  post 'wechatpay/notify' => 'pay#notify'

  root 'site#index'

  # product cat
  get 'customer/cats' => 'site#index_cats'
  get 'customer/cats/:cid/products' => 'site#index_cat_products'

  # customer shipaddress
  get 'customer/shipaddresses/new' => 'site#new_ship_address'
  match 'customer/shipaddresses/create', to: 'site#create_ship_address', via: :post
  match 'customer/shipaddresses/create/json', to: 'site#create_ship_address_via_ajax', via: :post
  get 'customer/shipaddresses' => 'site#index_ship_address'

  # product
  get 'customer/products/:id/show' => 'site#show_product'

  # product comment
  get 'customer/products/:id/comments/new' => 'site#new_comment'
  match 'customer/products/:id/comments/create', to: 'site#create_comment', via: :post
  get 'customer/products/:id/comments' => 'site#index_comments'
  get 'customer/products/search' => 'site#index_search_result'

  # group
  get 'customer/groups/:id/show' => 'site#show_group'
  get 'customer/groups_and_seckills' => 'site#index_groups_seckills'
  get 'customer/seckills/:id/show' => 'site#show_seckill'


  # order
  match 'customer/invoice/create/json', to: 'site#create_invoice_via_ajax', via: :post
  get 'customer/orders/settlement' => 'site#order_settlement'
  match 'customer/orders/create', to: 'site#create_order', via: :post

  get 'customer/commission' => 'site#commission'

  # user center
  get 'customer/cart' => 'site#index_shopping_cart'
  get 'customer/users/center' => 'site#user_center'
  get 'customer/users/wait/ship' => 'site#index_wait_ship'
  get 'customer/users/wait/pay' => 'site#index_wait_pay'
  get 'customer/users/wait/receive' => 'site#index_wait_receive'
  get 'customer/users/orders/history' => 'site#index_order_history'
  get 'customer/users/vipcard' => 'site#show_vip_card'

  # withdraw
  get 'customer/withdraws/new' => 'site#new_withdraw'
  get 'customer/withdraws' => 'site#index_withdraws'
  match 'customer/withdraws/create', to: 'site#create_withdraw', via: :post

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # activity prize
  get 'customer/big/wheel' => 'site#big_wheel'
  match 'customer/big/wheel', to: 'site#big_wheel_ajax', via: :post
  get 'customer/scratch/off' => 'site#scratch_off'
  match 'customer/scratch/off', to: 'site#scratch_off_ajax', via: :post

  scope '/admin' do

    # get 'commissions/year/index' => 'commissions#year_compute_index'
    # get 'commissions/year/compute' => 'commissions#year_compute'

    resources :commissions

    resources :withdraws
    get 'withdraws/:id/ok' => 'withdraws#ok_withdraw'

    resources :site_configs
    get 'site_configs/customer/index/imgs/edit' => 'site_configs#edit_index_imgs'
    get 'site_configs/customer/index/imgs' => 'site_configs#show_index_imgs'
    match 'site_configs/customer/index/imgs/update', to: 'site_configs#update_index_imgs', via: :post

    get 'site_configs/commissions/config' => 'site_configs#commissions_config_index'
    match 'site_configs/commissions/config', to: 'site_configs#commissions_config', via: :post

    get 'site_configs/integrals/config' => 'site_configs#integral_config_index'
    match 'site_configs/integrals/config', to: 'site_configs#integral_config', via: :post

    resources :seckill_orders
    resources :seckills

    resources :group_orders
    resources :groups

    match 'wx_menus/name/create/json', to: 'wx_menus#create_menu_name', via: :post
    match 'wx_menus/update/json', to: 'wx_menus#update_via_json', via: :post
    get 'weixin/menus/create/json' => 'wx_menus#create_weixin_menu'
    get 'wx_menus/:id/del/json' => 'wx_menus#destroy_via_ajax'
    match 'wx_menus/create/json', to: 'wx_menus#create_via_ajax', via: :post
    match 'wx_menus/:id/action/set', to: 'wx_menus#set_menu_action', via: :post
    match 'wx_menus/images/upload', to: 'wx_menus#upload_img', via: :post
    resources :wx_menus

    resources :prize_user_numbers
    resources :prize_users
    resources :prize_configs
    resources :prize_acts

    resources :integrals
    resources :vritualcards
    resources :shipaddresses

    resources :product_orders
    resources :orders
    get 'orders/wait/sure' => 'orders#index_orders_unsure'
    get 'orders/:id/sure' => 'orders#sure_order', as: :sure_order
    get 'orders/wait/ship' => 'orders#index_orders_wait_ship'
    match 'orders/:id/express/add', to: 'orders#add_order_express', via: :post
    get 'orders/:id/shiped' => 'orders#ship_order', as: :ship_order
    get 'orders/already/ship' => 'orders#index_orders_already_ship'
    get 'orders/:id/received' => 'orders#receive_order'
    get 'orders/already/receive' => 'orders#index_orders_already_receive'
    get 'orders/:id/oked' => 'orders#ok_order'
    get 'orders/already/ok' => 'orders#index_orders_already_ok'
    get 'orders/wait/back' => 'orders#index_orders_back'
    get 'orders/already/cancel' => 'orders#index_orders_canceled'

    resources :invoices
    resources :products
    resources :inventories
    resources :comments
    resources :tags

    get 'ueditor_uploader/index'
    match 'ueditor_uploader/index', to: 'ueditor_uploader#index', via: :post

    resources :roles
    resources :users
    resources :profiles

    resources :cats do
      collection do
        get :nested_options
        get :manage
        get :node_manage
        get :expand

        post :rebuild
        post :expand_node
      end
    end
  end

  get 'weixin' => 'weixin#show'
  match 'weixin', to: 'weixin#create', via: :post
end

app/models/prize_config.rb
class PrizeConfig < ActiveRecord::Base

  belongs_to :prize_act
end

app/controllers/prize_configs_controller.rb
class PrizeConfigsController < ApplicationController
  authorize_resource
  respond_to :html, :json
  before_action :set_prize_config, only: [:show, :edit, :update, :destroy]

  def index
    @prize_configs = PrizeConfig.all.paginate(page: params[:page], per_page: 10).order('id DESC')
    respond_with(@prize_configs)
  end

  def show
    respond_with(@prize_config)
  end

  def new
    @prize_config = PrizeConfig.new
    @prize_acts = PrizeAct.where(is_open: 1)
    @act_arr = []
    @prize_acts.each do |pa|
      @act_arr.push [pa.name, pa.id]
    end
    respond_with(@prize_config)
  end

  def edit
    @prize_acts = PrizeAct.where(is_open: 1)
    @act_arr = []
    @prize_acts.each do |pa|
      @act_arr.push [pa.name, pa.id]
    end
  end

  def create
    @prize_config = PrizeConfig.new(prize_config_params)
    flash[:notice] = 'PrizeConfig was successfully created.' if @prize_config.save
    respond_with(@prize_config)
  end

  def update
    flash[:notice] = 'PrizeConfig was successfully updated.' if @prize_config.update(prize_config_params)
    respond_with(@prize_config)
  end

  def destroy
    @prize_config.destroy
    respond_with(@prize_config)
  end

  private

  def set_prize_config
    @prize_config = PrizeConfig.find(params[:id])
  end

  def prize_config_params
    params.require(:prize_config).permit(:prize_act_id, :prize_name, :min, :max, :prize_content, :prize_inventory, :chance)
  end
end

app/views/prize_configs/_form.html.erb
<%= form_for(@prize_config, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @prize_config.errors.any? %>
    <div id="error_explanation" class="form-group">
      <div class="col-sm-2"></div>
      <div class="col-sm-9">
        <h2>保存时发生了<%= pluralize(@prize_config.errors.count, "error") %></h2>
        <ul>
          <% @prize_config.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :prize_act_id, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.prize_config.prize_act_id' %>
      <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.select(:prize_act_id, options_for_select(@act_arr, @prize_config.prize_act.id)) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prize_name, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.prize_config.prize_name' %>
      <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.text_field :prize_name, required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prize_content, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.prize_config.prize_content' %>
      <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.text_field :prize_content, required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prize_inventory, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.prize_config.prize_inventory' %>
      <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :prize_inventory, in: 0..20000000, required: "true", placeholder: "请输入一整数", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :chance, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.prize_config.chance' %>
      <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :chance, in: 0..20000000, required: "true", placeholder: "请输入一整数，可以为0", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" for="submit"></label>
    <div class="col-sm-9">
      <%= f.submit("提交", class: "btn btn-yellow btn-block") %>
    </div>
  </div>
<% end %>

app/views/prize_configs/edit.html.erb
<% content_for :page_title do %>
  编辑<%=t 'activerecord.models.prize_config' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        编辑<%=t 'activerecord.models.prize_config' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        编辑<%=t 'activerecord.models.prize_config' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">

        <%= render 'form' %>

      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->

app/views/prize_configs/index.html.erb
<% content_for :page_title do %>
  <%=t 'activerecord.models.prize_config' %>管理
<% end %>
<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
  <ol class="breadcrumb">
    <li>
      <i class="clip-pencil"></i>
      <a href="#">
        控制面板
      </a>
    </li>
    <li class="active">
      <%=t 'activerecord.models.prize_config' %>管理
    </li>
    <li class="search-box">
      <form class="sidebar-search">
        <div class="form-group">
          <input type="text" placeholder="Start Searching...">
          <button class="submit">
            <i class="clip-search-3"></i>
          </button>
        </div>
      </form>
    </li>
  </ol>
  <div class="page-header">
    <h1>
      <small></small>
    </h1>
  </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-external-link-square"></i>
    <%=t 'activerecord.models.prize_config' %>管理
    <div class="panel-tools">
      <a href="#" class="btn btn-xs btn-link panel-collapse collapses">
      </a>
      <a data-toggle="modal" href="#panel-config" class="btn btn-xs btn-link panel-config">
        <i class="fa fa-wrench"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-refresh">
        <i class="fa fa-refresh"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-expand">
        <i class="fa fa-resize-full"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-close">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%=t 'activerecord.attributes.prize_config.prize_act_id' %></th>
            <th><%=t 'activerecord.attributes.prize_config.prize_name' %></th>
            <th><%=t 'activerecord.attributes.prize_config.prize_content' %></th>
            <th><%=t 'activerecord.attributes.prize_config.prize_inventory' %></th>
            <th><%=t 'activerecord.attributes.prize_config.chance' %></th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @prize_configs.each do |prize_config| %>
            <tr>
              <td><%= prize_config.prize_act.name %></td>
              <td><%= prize_config.prize_name %></td>
              <td><%= prize_config.prize_content %></td>
              <td><%= prize_config.prize_inventory %></td>
              <td><%= prize_config.chance %></td>
              <td class="center">
                <%= link_to(prize_config, class: "btn btn-xs btn-primary") do %>
                  <i class="fa fa-share"></i>
                  查看
                <% end %>
                <%= link_to(edit_prize_config_path(prize_config), class: "btn btn-xs btn-green") do %>
                  <i class="fa fa-edit"></i>
                  编辑
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= will_paginate @prize_configs, renderer: BootstrapPagination::Rails %>
</div>

app/views/prize_configs/new.html.erb
<% content_for :page_title do %>
  添加<%=t 'activerecord.models.prize_config' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        添加<%=t 'activerecord.models.prize_config' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        添加<%=t 'activerecord.models.prize_config' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">

        <%= render 'form' %>

      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->

app/views/prize_configs/show.html.erb
<% content_for :page_title do %>
  查看<%=t 'activerecord.models.prize_config' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        查看<%=t 'activerecord.models.prize_config' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        查看<%=t 'activerecord.models.prize_config' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">
        <div class="form-horizontal">
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.prize_act_id' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.prize_act_id %>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.prize_name' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.prize_name %>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.min' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.min %>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.max' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.max %>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.prize_content' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.prize_content %>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.prize_inventory' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.prize_inventory %>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.prize_config.chance' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @prize_config.chance %>
              </div>
            </div>
          </div>
                  </div>
      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->