config/routes.rb
Rails.application.routes.draw do

  # wechat pay test
  # get 'testpay/js_api_call_pay' => 'pay#pay'
  get 'wechatpay/js_api_call_pay' => 'pay#pay'
  get 'pay/success' => 'pay#pay_success'
  # post 'testpay/notify' => 'pay#notify'
  post 'wechatpay/notify' => 'pay#notify'

  root 'site#index'

  # product cat
  get 'customer/cats' => 'site#index_cats'
  get 'customer/cats/:cid/products' => 'site#index_cat_products'

  # customer shipaddress
  get 'customer/shipaddresses/new' => 'site#new_ship_address'
  match 'customer/shipaddresses/create', to: 'site#create_ship_address', via: :post
  match 'customer/shipaddresses/create/json', to: 'site#create_ship_address_via_ajax', via: :post
  get 'customer/shipaddresses' => 'site#index_ship_address'

  # product
  get 'customer/products/:id/show' => 'site#show_product'

  # product comment
  get 'customer/products/:id/comments/new' => 'site#new_comment'
  match 'customer/products/:id/comments/create', to: 'site#create_comment', via: :post
  get 'customer/products/:id/comments' => 'site#index_comments'
  get 'customer/products/search' => 'site#index_search_result'

  # group
  get 'customer/groups/:id/show' => 'site#show_group'
  get 'customer/groups_and_seckills' => 'site#index_groups_seckills'
  get 'customer/seckills/:id/show' => 'site#show_seckill'


  # order
  match 'customer/invoice/create/json', to: 'site#create_invoice_via_ajax', via: :post
  get 'customer/orders/settlement' => 'site#order_settlement'
  match 'customer/orders/create', to: 'site#create_order', via: :post

  get 'customer/commission' => 'site#commission'

  # user center
  get 'customer/cart' => 'site#index_shopping_cart'
  get 'customer/users/center' => 'site#user_center'
  get 'customer/users/wait/ship' => 'site#index_wait_ship'
  get 'customer/users/wait/pay' => 'site#index_wait_pay'
  get 'customer/users/wait/receive' => 'site#index_wait_receive'
  get 'customer/users/orders/history' => 'site#index_order_history'
  get 'customer/users/vipcard' => 'site#show_vip_card'

  # withdraw
  get 'customer/withdraws/new' => 'site#new_withdraw'
  get 'customer/withdraws' => 'site#index_withdraws'
  match 'customer/withdraws/create', to: 'site#create_withdraw', via: :post

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # activity prize
  get 'customer/big/wheel' => 'site#big_wheel'
  match 'customer/big/wheel', to: 'site#big_wheel_ajax', via: :post
  get 'customer/scratch/off' => 'site#scratch_off'
  match 'customer/scratch/off', to: 'site#scratch_off_ajax', via: :post

  scope '/admin' do

    # get 'commissions/year/index' => 'commissions#year_compute_index'
    # get 'commissions/year/compute' => 'commissions#year_compute'

    resources :commissions

    resources :withdraws
    get 'withdraws/:id/ok' => 'withdraws#ok_withdraw'

    resources :site_configs
    get 'site_configs/customer/index/imgs/edit' => 'site_configs#edit_index_imgs'
    get 'site_configs/customer/index/imgs' => 'site_configs#show_index_imgs'
    match 'site_configs/customer/index/imgs/update', to: 'site_configs#update_index_imgs', via: :post

    get 'site_configs/commissions/config' => 'site_configs#commissions_config_index'
    match 'site_configs/commissions/config', to: 'site_configs#commissions_config', via: :post

    get 'site_configs/integrals/config' => 'site_configs#integral_config_index'
    match 'site_configs/integrals/config', to: 'site_configs#integral_config', via: :post

    resources :seckill_orders
    resources :seckills

    resources :group_orders
    resources :groups

    match 'wx_menus/name/create/json', to: 'wx_menus#create_menu_name', via: :post
    match 'wx_menus/update/json', to: 'wx_menus#update_via_json', via: :post
    get 'weixin/menus/create/json' => 'wx_menus#create_weixin_menu'
    get 'wx_menus/:id/del/json' => 'wx_menus#destroy_via_ajax'
    match 'wx_menus/create/json', to: 'wx_menus#create_via_ajax', via: :post
    match 'wx_menus/:id/action/set', to: 'wx_menus#set_menu_action', via: :post
    match 'wx_menus/images/upload', to: 'wx_menus#upload_img', via: :post
    resources :wx_menus

    resources :prize_user_numbers
    resources :prize_users
    resources :prize_configs
    resources :prize_acts

    resources :integrals
    resources :vritualcards
    resources :shipaddresses

    resources :product_orders
    resources :orders
    get 'orders/wait/sure' => 'orders#index_orders_unsure'
    get 'orders/:id/sure' => 'orders#sure_order', as: :sure_order
    get 'orders/wait/ship' => 'orders#index_orders_wait_ship'
    match 'orders/:id/express/add', to: 'orders#add_order_express', via: :post
    get 'orders/:id/shiped' => 'orders#ship_order', as: :ship_order
    get 'orders/already/ship' => 'orders#index_orders_already_ship'
    get 'orders/:id/received' => 'orders#receive_order'
    get 'orders/already/receive' => 'orders#index_orders_already_receive'
    get 'orders/:id/oked' => 'orders#ok_order'
    get 'orders/already/ok' => 'orders#index_orders_already_ok'
    get 'orders/wait/back' => 'orders#index_orders_back'
    get 'orders/already/cancel' => 'orders#index_orders_canceled'

    resources :invoices
    resources :products
    resources :inventories
    resources :comments
    resources :tags

    get 'ueditor_uploader/index'
    match 'ueditor_uploader/index', to: 'ueditor_uploader#index', via: :post

    resources :roles
    resources :users
    resources :profiles

    resources :cats do
      collection do
        get :nested_options
        get :manage
        get :node_manage
        get :expand

        post :rebuild
        post :expand_node
      end
    end
  end

  get 'weixin' => 'weixin#show'
  match 'weixin', to: 'weixin#create', via: :post
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :product_id, :description, :price, :is_commission, presence: true

  has_many :group_orders
  has_many :orders, through: :group_orders

  belongs_to :product
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  authorize_resource
  respond_to :html, :json
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all.paginate(page: params[:page], per_page: 10).order('id DESC')
    respond_with(@groups)
  end

  def show
    @products = Product.all
    respond_with(@group)
  end

  def new
    @products = Product.all
    @group = Group.new
    respond_with(@group)
  end

  def edit
    @products = Product.all
  end

  def create
    @group = Group.new(group_params)
    @group.people = 0
    @group.remain = @group.limit_product_count
    flash[:notice] = 'Group was successfully created.' if @group.save
    respond_with(@group)
  end

  def update
    flash[:notice] = 'Group was successfully updated.' if @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:product_id, :start_time, :end_time, :limit_people_count, :limit_product_count, :description, :price, :saveup, :discount, :limit_per_person, :is_commission)
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation" class="form-group">
      <div class="col-sm-2"></div>
      <div class="col-sm-9">
        <h2>保存时发生了<%= pluralize(@group.errors.count, "error") %></h2>
        <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :product_id, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.product_id' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.select(:product_id, options_for_select(@products.collect{|p| [p.name, p.id]}, @group.product_id)) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_time, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.start_time' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.datetime_select :start_time, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.end_time' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.datetime_select :end_time, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :limit_people_count, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.limit_people_count' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :limit_people_count, in: 1..20000000, placeholder: "请输入一数字", required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :limit_product_count, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.limit_product_count' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :limit_product_count, in: 1..20000000, placeholder: "请输入一数字", required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :limit_per_person, :class => "col-sm-2 control-label" do %>
    <%=t 'activerecord.attributes.group.limit_per_person' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :limit_per_person, in: 1..20000000, placeholder: "请输入一数字", required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.description' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.text_area :description, required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.price' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :price, in: 0.01..20000000.01, step: 0.01, placeholder: "请输入一数字，小数位数不超过两位", required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :saveup, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.saveup' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :saveup, in: 0.01..20000000.01, step: 0.01, placeholder: "请输入一数字，小数位数不超过两位", required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :discount, :class => "col-sm-2 control-label" do %>
      <%=t 'activerecord.attributes.group.discount' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.number_field :discount, required: "true", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_commission, :class => "col-sm-2 control-label" do %>
    <%=t 'activerecord.attributes.group.is_commission' %> <span class="symbol required"></span>
    <% end %>
    <div class="col-sm-9">
      <%= f.select(:is_commission, options_for_select([['参与提成', 1], ['不参与提成', 0]], @group.is_commission)) %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" for="submit"></label>
    <div class="col-sm-9">
      <%= f.submit("提交", class: "btn btn-yellow btn-block") %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% content_for :page_title do %>
  编辑<%=t 'activerecord.models.group' %>
<% end %>
<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
  <ol class="breadcrumb">
    <li>
      <i class="clip-pencil"></i>
      <a href="#">
        控制面板
        </a>
    </li>
    <li class="active">
      编辑<%=t 'activerecord.models.group' %>
    </li>
    <li class="search-box">
      <form class="sidebar-search">
        <div class="form-group">
          <input type="text" placeholder="Start Searching...">
          <button class="submit">
            <i class="clip-search-3"></i>
          </button>
        </div>
      </form>
    </li>
  </ol>
  <div class="page-header">
    <h1>
      <small></small>
    </h1>
  </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->
<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        编辑<%=t 'activerecord.models.group' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->

app/views/groups/index.html.erb
<% content_for :page_title do %>
  <%=t 'activerecord.models.group' %>管理
<% end %>
<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
  <ol class="breadcrumb">
    <li>
      <i class="clip-pencil"></i>
      <a href="#">
        控制面板
        </a>
    </li>
    <li class="active">
      <%=t 'activerecord.models.group' %>管理
      </li>
    <li class="search-box">
      <form class="sidebar-search">
        <div class="form-group">
          <input type="text" placeholder="Start Searching...">
          <button class="submit">
            <i class="clip-search-3"></i>
          </button>
        </div>
      </form>
    </li>
  </ol>
  <div class="page-header">
    <h1>
      <small></small>
    </h1>
  </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-external-link-square"></i>
    <%=t 'activerecord.models.group' %>管理

    <div class="panel-tools">
      <a href="#" class="btn btn-xs btn-link panel-collapse collapses">
      </a>
      <a data-toggle="modal" href="#panel-config" class="btn btn-xs btn-link panel-config">
        <i class="fa fa-wrench"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-refresh">
        <i class="fa fa-refresh"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-expand">
        <i class="fa fa-resize-full"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-close">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12 space20">
        <a class="btn btn-green add-row" href="/admin/groups/new">
          添加 <i class="fa fa-plus"></i>
        </a>
      </div>
    </div>
    <div class="table-responsive">
      <table id="" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%=t 'activerecord.attributes.group.product_id' %></th>
            <th><%=t 'activerecord.attributes.group.is_commission' %></th>
            <th><%=t 'activerecord.attributes.group.start_time' %></th>
            <th><%=t 'activerecord.attributes.group.end_time' %></th>
            <th><%=t 'activerecord.attributes.group.limit_people_count' %></th>
            <th><%=t 'activerecord.attributes.group.limit_product_count' %></th>
            <th><%=t 'activerecord.attributes.group.limit_per_person' %></th>
            <th><%=t 'activerecord.attributes.group.remain' %></th>
            <th><%=t 'activerecord.attributes.group.description' %></th>
            <th><%=t 'activerecord.attributes.group.price' %></th>
            <th><%=t 'activerecord.attributes.group.saveup' %></th>
            <th><%=t 'activerecord.attributes.group.discount' %></th>
            <th><%=t 'activerecord.attributes.group.people' %></th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= group.product.name %></td>
              <td><% if group.is_commission == 1 %>参与提成<% elsif group.is_commission == 0 %>不参与提成<% end %></td>
              <td><%= group.start_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
              <td><%= group.end_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
              <td><%= group.limit_people_count %></td>
              <td><%= group.limit_product_count %></td>
              <td><%= group.limit_per_person %></td>
              <td><%= group.remain %></td>
              <td><%= group.description %></td>
              <td><%= group.price %></td>
              <td><%= group.saveup %></td>
              <td><%= group.discount %></td>
              <td><%= group.people %></td>
              <td class="center">
                <%= link_to(group, method: :delete, data: { confirm: '确定吗?' }, class: "btn btn-xs btn-bricky") do %>
                  <i class="fa fa-trash-o"></i> 删除
              <% end %>
                <%= link_to(group, class: "btn btn-xs btn-primary") do %>
                  <i class="fa fa-share"></i> 查看
              <% end %>
                <%= link_to(edit_group_path(group), class: "btn btn-xs btn-green") do %>
                  <i class="fa fa-edit"></i> 编辑
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= will_paginate @groups, renderer: BootstrapPagination::Rails %>
</div>

app/views/groups/new.html.erb
<% content_for :page_title do %>
  添加<%=t 'activerecord.models.group' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        添加<%=t 'activerecord.models.group' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        添加<%=t 'activerecord.models.group' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">

        <%= render 'form' %>

      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->

app/views/groups/show.html.erb
<% content_for :page_title do %>
  查看<%=t 'activerecord.models.group' %>
<% end %>
<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
  <ol class="breadcrumb">
    <li>
      <i class="clip-pencil"></i>
      <a href="#">
        控制面板
        </a>
    </li>
    <li class="active">
      查看<%=t 'activerecord.models.group' %>
    </li>
    <li class="search-box">
      <form class="sidebar-search">
        <div class="form-group">
          <input type="text" placeholder="Start Searching...">
          <button class="submit">
            <i class="clip-search-3"></i>
          </button>
        </div>
      </form>
    </li>
  </ol>
  <div class="page-header">
    <h1>
      <small></small>
    </h1>
  </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->
<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        查看<%=t 'activerecord.models.group' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">
        <div class="form-horizontal">
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.product_id' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.product.name %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.is_commission' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <% if @group.is_commission == 1 %>参与提成<% elsif @group.is_commission == 0 %>不参与提成<% end %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.start_time' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.start_time.strftime("%Y-%m-%d") %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.end_time' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.end_time.strftime("%Y-%m-%d") %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.limit_people_count' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.limit_people_count %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.limit_product_count' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.limit_product_count %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.limit_per_person' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.limit_per_person %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.remain' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.remain %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.description' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= raw @group.description %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.price' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.price %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.saveup' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.saveup %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.discount' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.discount %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"><%=t 'activerecord.attributes.group.people' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @group.people %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->