config/routes.rb
Rails.application.routes.draw do

  # wechat pay test
  # get 'testpay/js_api_call_pay' => 'pay#pay'
  get 'wechatpay/js_api_call_pay' => 'pay#pay'
  get 'pay/success' => 'pay#pay_success'
  # post 'testpay/notify' => 'pay#notify'
  post 'wechatpay/notify' => 'pay#notify'

  root 'site#index'

  # product cat
  get 'customer/cats' => 'site#index_cats'
  get 'customer/cats/:cid/products' => 'site#index_cat_products'

  # customer shipaddress
  get 'customer/shipaddresses/new' => 'site#new_ship_address'
  match 'customer/shipaddresses/create', to: 'site#create_ship_address', via: :post
  match 'customer/shipaddresses/create/json', to: 'site#create_ship_address_via_ajax', via: :post
  get 'customer/shipaddresses' => 'site#index_ship_address'

  # product
  get 'customer/products/:id/show' => 'site#show_product'

  # product comment
  get 'customer/products/:id/comments/new' => 'site#new_comment'
  match 'customer/products/:id/comments/create', to: 'site#create_comment', via: :post
  get 'customer/products/:id/comments' => 'site#index_comments'
  get 'customer/products/search' => 'site#index_search_result'

  # group
  get 'customer/groups/:id/show' => 'site#show_group'
  get 'customer/groups_and_seckills' => 'site#index_groups_seckills'
  get 'customer/seckills/:id/show' => 'site#show_seckill'


  # order
  match 'customer/invoice/create/json', to: 'site#create_invoice_via_ajax', via: :post
  get 'customer/orders/settlement' => 'site#order_settlement'
  match 'customer/orders/create', to: 'site#create_order', via: :post

  get 'customer/commission' => 'site#commission'

  # user center
  get 'customer/cart' => 'site#index_shopping_cart'
  get 'customer/users/center' => 'site#user_center'
  get 'customer/users/wait/ship' => 'site#index_wait_ship'
  get 'customer/users/wait/pay' => 'site#index_wait_pay'
  get 'customer/users/wait/receive' => 'site#index_wait_receive'
  get 'customer/users/orders/history' => 'site#index_order_history'
  get 'customer/users/vipcard' => 'site#show_vip_card'

  # withdraw
  get 'customer/withdraws/new' => 'site#new_withdraw'
  get 'customer/withdraws' => 'site#index_withdraws'
  match 'customer/withdraws/create', to: 'site#create_withdraw', via: :post

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # activity prize
  get 'customer/big/wheel' => 'site#big_wheel'
  match 'customer/big/wheel', to: 'site#big_wheel_ajax', via: :post
  get 'customer/scratch/off' => 'site#scratch_off'
  match 'customer/scratch/off', to: 'site#scratch_off_ajax', via: :post

  scope '/admin' do

    # get 'commissions/year/index' => 'commissions#year_compute_index'
    # get 'commissions/year/compute' => 'commissions#year_compute'

    resources :commissions

    resources :withdraws
    get 'withdraws/:id/ok' => 'withdraws#ok_withdraw'

    resources :site_configs
    get 'site_configs/customer/index/imgs/edit' => 'site_configs#edit_index_imgs'
    get 'site_configs/customer/index/imgs' => 'site_configs#show_index_imgs'
    match 'site_configs/customer/index/imgs/update', to: 'site_configs#update_index_imgs', via: :post

    get 'site_configs/commissions/config' => 'site_configs#commissions_config_index'
    match 'site_configs/commissions/config', to: 'site_configs#commissions_config', via: :post

    get 'site_configs/integrals/config' => 'site_configs#integral_config_index'
    match 'site_configs/integrals/config', to: 'site_configs#integral_config', via: :post

    resources :seckill_orders
    resources :seckills

    resources :group_orders
    resources :groups

    match 'wx_menus/name/create/json', to: 'wx_menus#create_menu_name', via: :post
    match 'wx_menus/update/json', to: 'wx_menus#update_via_json', via: :post
    get 'weixin/menus/create/json' => 'wx_menus#create_weixin_menu'
    get 'wx_menus/:id/del/json' => 'wx_menus#destroy_via_ajax'
    match 'wx_menus/create/json', to: 'wx_menus#create_via_ajax', via: :post
    match 'wx_menus/:id/action/set', to: 'wx_menus#set_menu_action', via: :post
    match 'wx_menus/images/upload', to: 'wx_menus#upload_img', via: :post
    resources :wx_menus

    resources :prize_user_numbers
    resources :prize_users
    resources :prize_configs
    resources :prize_acts

    resources :integrals
    resources :vritualcards
    resources :shipaddresses

    resources :product_orders
    resources :orders
    get 'orders/wait/sure' => 'orders#index_orders_unsure'
    get 'orders/:id/sure' => 'orders#sure_order', as: :sure_order
    get 'orders/wait/ship' => 'orders#index_orders_wait_ship'
    match 'orders/:id/express/add', to: 'orders#add_order_express', via: :post
    get 'orders/:id/shiped' => 'orders#ship_order', as: :ship_order
    get 'orders/already/ship' => 'orders#index_orders_already_ship'
    get 'orders/:id/received' => 'orders#receive_order'
    get 'orders/already/receive' => 'orders#index_orders_already_receive'
    get 'orders/:id/oked' => 'orders#ok_order'
    get 'orders/already/ok' => 'orders#index_orders_already_ok'
    get 'orders/wait/back' => 'orders#index_orders_back'
    get 'orders/already/cancel' => 'orders#index_orders_canceled'

    resources :invoices
    resources :products
    resources :inventories
    resources :comments
    resources :tags

    get 'ueditor_uploader/index'
    match 'ueditor_uploader/index', to: 'ueditor_uploader#index', via: :post

    resources :roles
    resources :users
    resources :profiles

    resources :cats do
      collection do
        get :nested_options
        get :manage
        get :node_manage
        get :expand

        post :rebuild
        post :expand_node
      end
    end
  end

  get 'weixin' => 'weixin#show'
  match 'weixin', to: 'weixin#create', via: :post
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  authorize_resource

  respond_to :html, :json
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all.paginate(:page => params[:page], :per_page => 10).order('id DESC')
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :taggings_count)
    end
end

app/views/tags/_form.html.erb
<%= form_for(@tag, :html => {:class => "form-horizontal"}) do |f| %>
    <% if @tag.errors.any? %>
        <div id="error_explanation" class="form-group">
          <div class="col-sm-2"></div>
          <div class="col-sm-9">
            <h2>保存时发生了<%= pluralize(@tag.errors.count, "error") %></h2>
            <ul>
              <% @tag.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => "col-sm-2 control-label" do %>
          <%= t 'activerecord.attributes.tag.name' %> <span class="symbol required"></span>
      <% end %>
      <div class="col-sm-9">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :taggings_count, :class => "col-sm-2 control-label" do %>
          <%= t 'activerecord.attributes.tag.taggings_count' %> <span class="symbol required"></span>
      <% end %>
      <div class="col-sm-9">
        <%= f.number_field :taggings_count, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label" for="submit"></label>

      <div class="col-sm-9">
        <%= f.submit("提交", class: "btn btn-yellow btn-block") %>
      </div>
    </div>
<% end %>

app/views/tags/edit.html.erb
<% content_for :page_title do %>
    编辑<%= t 'activerecord.models.tag' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        编辑<%= t 'activerecord.models.tag' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        编辑<%= t 'activerecord.models.tag' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">

        <%= render 'form' %>

      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->

app/views/tags/index.html.erb
<% content_for :page_title do %>
  <%= t 'activerecord.models.tag' %>管理
<% end %>
<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
  <ol class="breadcrumb">
    <li>
      <i class="clip-pencil"></i>
      <a href="#">
        控制面板
      </a>
    </li>
    <li class="active">
      <%= t 'activerecord.models.tag' %>管理
    </li>
    <li class="search-box">
      <form class="sidebar-search">
        <div class="form-group">
          <input type="text" placeholder="Start Searching...">
          <button class="submit">
            <i class="clip-search-3"></i>
          </button>
        </div>
      </form>
    </li>
  </ol>
  <div class="page-header">
    <h1>
      <small></small>
    </h1>
  </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-external-link-square"></i>
    <%= t 'activerecord.models.tag' %>管理
    <div class="panel-tools">
      <a href="#" class="btn btn-xs btn-link panel-collapse collapses">
      </a>
      <a data-toggle="modal" href="#panel-config" class="btn btn-xs btn-link panel-config">
        <i class="fa fa-wrench"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-refresh">
        <i class="fa fa-refresh"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-expand">
        <i class="fa fa-resize-full"></i>
      </a>
      <a href="#" class="btn btn-xs btn-link panel-close">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= t 'activerecord.attributes.tag.name' %></th>
            <th><%= t 'activerecord.attributes.tag.taggings_count' %></th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td><%= tag.name %></td>
              <td><%= tag.taggings_count %></td>
              <td class="center">
                <%= link_to(tag, method: :delete, data: {confirm: '确定吗?'}, class: "btn btn-xs btn-bricky") do %>
                  <i class="fa fa-trash-o"></i>
                  删除
                <% end %>
                <%= link_to(tag, class: "btn btn-xs btn-primary") do %>
                  <i class="fa fa-share"></i>
                  查看
                <% end %>
                <%= link_to(edit_tag_path(tag), class: "btn btn-xs btn-green") do %>
                  <i class="fa fa-edit"></i>
                  编辑
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= will_paginate @tags, renderer: BootstrapPagination::Rails %>
</div>

app/views/tags/new.html.erb
<% content_for :page_title do %>
    添加<%= t 'activerecord.models.tag' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        添加<%= t 'activerecord.models.tag' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        添加<%= t 'activerecord.models.tag' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">

        <%= render 'form' %>

      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->

app/views/tags/show.html.erb
<% content_for :page_title do %>
    查看<%= t 'activerecord.models.tag' %>
<% end %>

<!-- start: PAGE TITLE & BREADCRUMB -->
<% content_for :page_crumbs do %>
    <ol class="breadcrumb">
      <li>
        <i class="clip-pencil"></i>
        <a href="#">
          控制面板
        </a>
      </li>
      <li class="active">
        查看<%= t 'activerecord.models.tag' %>
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>
        <small></small>
      </h1>
    </div>
<% end %>
<!-- end: PAGE TITLE & BREADCRUMB -->

<!-- start: PAGE CONTENT -->
<div class="row">
  <div class="col-sm-12">
    <!-- start: TEXT FIELDS PANEL -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        查看<%= t 'activerecord.models.tag' %>
        <div class="panel-tools">
          <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
          </a>
          <a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
            <i class="fa fa-wrench"></i>
          </a>
          <a class="btn btn-xs btn-link panel-refresh" href="#">
            <i class="fa fa-refresh"></i>
          </a>
          <a class="btn btn-xs btn-link panel-expand" href="#">
            <i class="fa fa-resize-full"></i>
          </a>
          <a class="btn btn-xs btn-link panel-close" href="#">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="panel-body">
        <div class="form-horizontal">

          <div class="form-group">
            <div class="col-sm-2 control-label"><%= t 'activerecord.attributes.tag.name' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @tag.name %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label"><%= t 'activerecord.attributes.tag.taggings_count' %></div>
            <div class="col-sm-9">
              <div class="show-control">
                <%= @tag.taggings_count %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end: TEXT FIELDS PANEL -->
  </div>
</div>
<!-- end: PAGE CONTENT-->